### ISSUE TITLE
关于BERT模型训练问题

### ISSUE THREAD

**Issue by NaitangTian** [songyouwei/ABSA-PyTorch#105]
您好，感谢您提供这些代码。
关于BERT模型的训练我有一个问题，在输入命令后它会出现从一个网站下载模型的过程，这个过程非常慢，楼主有什么方法能推荐给我吗？因为是在是太慢了

**Comment by songyouwei** [comment]
你可以设置http_proxy下载，或者在 [transformers](https://github.com/huggingface/transformers) 项目里查查看别人是咋处理的，看看有没有国内的下载源吧

**Comment by NaitangTian** [comment]
好的，谢谢
