### ISSUE TITLE
AEN_BERT模型的疑问

### ISSUE THREAD

**Issue by NaitangTian** [songyouwei/ABSA-PyTorch#126]
拜读了您的AEN_BERT模型的论文，对于BERT模型生成的词向量有些疑问：
文中设定句子的长度为n，方面词长度为m，从BERT模型输出后为何还是长度为m和n，不包含[CLS]和[SEP]的向量吗

**Comment by songyouwei** [comment]
BERT_SPC是把问题作为句子对分类来做，需要[CLS]和[SEP]，AEN_BERT计算词向量的时候是对两部分单独编码的，不需要这两个特殊标记

**Comment by NaitangTian** [comment]
谢谢您的回复。
那这种从BERT呼出的词向量长度不变的情况，对其他类似的使用BERT生成词向量的ABSA模型都是一样的吗？

**Comment by songyouwei** [comment]
是不是要考虑[CLS] [SEP]还是看具体模型的设计吧，对于单个句子的编码来说，[SEP]是不需要的，[CLS]可有可无

**Comment by NaitangTian** [comment]
好的，非常感谢
