### ISSUE TITLE
为何使用lstm这样的句子级别的模型,预测的结果类别大于1,不应该只有一个分类结果吗?

### ISSUE THREAD

**Issue by xueyongfu** [songyouwei/ABSA-PyTorch#134]
这个问题我已经发现,主要是标点符号的问题, 那作者的源代码对这部分的处理是否不当?

**Comment by xueyongfu** [comment]
@songyouwei

**Comment by songyouwei** [comment]
问题描述我没有看懂，什么标点符号问题？

**Comment by xueyongfu** [comment]
比如:
I've had the same $T$ at Peter Lugers for double the price.
steak
0
I've had the same steak at Peter Lugers for double the $T$.
price
-1

使用lstm模型:
两条输入lstm模型的数据应该是一样的, 预测结果也是一样的.但是代码中的处理是这样的:
text_raw_indices = tokenizer.text_to_sequence(text_left + " " + aspect + " " + text_right)
在aspect前后加了空格,  这就使得两个句子的输入不同,自然预测结果也可能不同:
句1:I've had the same steak at Peter Lugers for double the price.
ju2:I've had the same steak at Peter Lugers for double the price .(注意price后有空格)

**Comment by xueyongfu** [comment]
price和price.  两个词向量都是存在的

**Comment by xueyongfu** [comment]
@songyouwei

**Comment by songyouwei** [comment]
额，确实有这样一些细节的问题应该处理一下的。模型的实验结果方面应该影响不大吧

**Comment by xueyongfu** [comment]
lstm模型:标点修改之后降低了约6%, 影响挺大的

**Comment by xueyongfu** [comment]
@songyouwei   lstm模型:标点修改之后降低了约6%, 影响挺大的
