### ISSUE TITLE
Why comment out the locationed_memory in memnet and ram

### ISSUE THREAD

**Issue by GeneZC** [songyouwei/ABSA-PyTorch#14]

**Comment by GeneZC** [comment]
What's more, there are some critical bugs and something not in accordance with the papers

**Comment by songyouwei** [comment]
I commented out the locationed_memory since it actually not performs well.
Cabasc is implemented by @AlbertoPaz and I haven't tried it. If you have any idea of fixing these critical bugs, please make a pull request~ thanks :smiley:

**Comment by songyouwei** [comment]
fixed #16
