### ISSUE TITLE
想请教一下，我使用其中的Bert模型运行中文数据集时，出现了Acc>90,而F1<60,的情况

### ISSUE THREAD

**Issue by fathouse** [songyouwei/ABSA-PyTorch#143]
想请教一下，我使用其中的Bert模型运行中文数据集时，出现了Acc>90,而F1<60,的情况，请问这是什么原因呢，预训练使用的Bert-chinese，model使用了Bert-spc以及lcf_bert，都出现了这样的问题，请问我该如何改进？

**Comment by fathouse** [comment]
camera:
batch_size:16
max_test_acc_overall:95.6896551724138
max_f1_overall:63.26241933988123
batch_size:32
max_test_acc_overall:95.0
max_f1_overall:62.65156587737234

car:
batch_size:16
max_test_acc_overall:97.19298245614036
max_f1_overall:64.27432216905902
batch_size:32
max_test_acc_overall:97.19298245614036
max_f1_overall:64.27432216905902

**Comment by fathouse** [comment]
@songyouwei

**Comment by songyouwei** [comment]
应该是跟你这个数据分布有关，可以参考[这里的回答](https://www.quora.com/How-do-I-interpret-a-high-accuracy-82-44-but-an-extremely-low-F1-score-0-259-in-my-deep-learning-model-How-do-I-go-about-improving-the-F1-score)

**Comment by fathouse** [comment]
> 应该是跟你这个数据分布有关，可以参考[这里的回答](https://www.quora.com/How-do-I-interpret-a-high-accuracy-82-44-but-an-extremely-low-F1-score-0-259-in-my-deep-learning-model-How-do-I-go-about-improving-the-F1-score)

你好，感谢你的解答，我发现可以通过（更改数据集）或调节阈值来降低准确率，提高召回率，但是我把代码找了一遍也没有发现在哪里可以调节阈值，请问您知道吗
