### ISSUE TITLE
请问随机种子应该如何设置呢？

### ISSUE THREAD

**Issue by furukawayuan-Yao** [songyouwei/ABSA-PyTorch#152]
打扰了！因为复现Tnet-lf每一次的结果都是不一样的，所以后来自己设置了随机种子seed=0、50、100、150试了一下，发现其设置对于test acc以及test macro F1都有一定的影响，但是这个应该如何设置呢？

**Comment by v-JiangNan** [comment]
随机种子不要去找，而应该多跑几个取平均。如果一个模型依赖初始化种子，那么这个模型基本没有任何价值。

**Comment by furukawayuan-Yao** [comment]
> 随机种子不要去找，而应该多跑几个取平均。如果一个模型依赖初始化种子，那么这个模型基本没有任何价值。

感谢！
