### ISSUE TITLE
GPU issue

### ISSUE THREAD

**Issue by yassmine-lam** [songyouwei/ABSA-PyTorch#173]
Hi,

I tried to run the aen model on GPU but I got this error

RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:0 Long tensor

could someone help plz?

Thank u

**Comment by v-JiangNan** [comment]
modify it to "lengths.cpu()"

**Comment by yassmine-lam** [comment]
yes u are right 
thank u

**Comment by tusharkgerg** [comment]
@yassmine-lam im facing the same issue. Where and how were you able to fix this?
