### ISSUE TITLE
ASGCN

### ISSUE THREAD

**Issue by WhatTong** [songyouwei/ABSA-PyTorch#179]
报错：ValueError: index can't contain negative values
应该是tokenizer.max_seq_len-idx2graph[i].shape[0]小于0导致，但max_seq_len设置很大也没有办法解决
dependency_graph = np.pad(idx2graph[i], ((0, tokenizer.max_seq_len-idx2graph[i].shape[0]), (0, tokenizer.max_seq_len-idx2graph[i].shape[0])), 'constant')

**Comment by GeneZC** [comment]
能把场景报一下吗

**Comment by Xiao-tengfei** [comment]
我也遇到这个问题了，在计算dependency_graph 前，我对 “idx2graph[i]”做出限制：            
if idx2graph[i].shape[0] > tokenizer.max_seq_len:
    idx2graph[i] = idx2graph[i][:tokenizer.max_seq_len, :tokenizer.max_seq_len]

**Comment by GitOffice** [comment]
也遇到同样的错误，目前是在cpu上运行的。训练集是1000条没问题，在6000条左右就出现这个错误。

**Comment by GeneZC** [comment]
@GitOffice 可能是某条数据图的预处理出了问题，可以使用原仓库 https://github.com/GeneZC/ASGCN  试试

**Comment by GitOffice** [comment]
@GeneZC  谢谢回复，那能否用你原仓库的dependency_graph.py替换这个库的py用呢？对于ASGCN模型来说，还有哪些文件有区别？

**Comment by GeneZC** [comment]
@GitOffice 预处理部分没有区别，区别主要在于后续部分，我目前还没排查出来这个repo的部分有什么问题。
