### ISSUE TITLE
How can the BERT be applied to aspect-level sentiment analysis?

### ISSUE THREAD

**Issue by YHTtTtao** [songyouwei/ABSA-PyTorch#28]
BERT in your application is to test wheather  the sentence B is the actual next sentence that follows sentence A, but what can I do to use the BERT in aspect-level sentiment analysis?

**Comment by songyouwei** [comment]
[BERT-SPC](https://github.com/songyouwei/ABSA-PyTorch/blob/master/models/bert_spc.py)
is designed for sequence pair classification task and is applicable of ABSA task.

You can also transform ABSA  sequence pair to NLI or QA.
