### ISSUE TITLE
大佬发论文的速度真是叹为观止

### ISSUE THREAD

**Issue by floAlpha** [songyouwei/ABSA-PyTorch#30]
动手能力太差，想到做不出来，请问大佬后期对ABSA有更深入研究的打算吗？

**Comment by songyouwei** [comment]
并不是大佬。。我只是在自己之前做的工作上修修补补。。。

我觉得虽然基于预训练的模型外部知识比较丰富，但还是有很多地方可以做的，比如BERT中间层的结果能不能利用起来，能不能迁移相似任务的知识进来，很多。

**Comment by songyouwei** [comment]
issue 不适合聊天，我回头开个Gitter，大家可以在那里讨论讨论
