### ISSUE TITLE
Why we use squeeze_embedding

### ISSUE THREAD

**Issue by GeneZC** [songyouwei/ABSA-PyTorch#31]
I'm currently somehow confused about why we use squeeze_embedding module to pack the padded sequences and then unpack it ?

**Comment by floAlpha** [comment]
mark，same confusion

**Comment by songyouwei** [comment]
It works like `layers/dynamic_rnn.py`, we use `torch.nn.utils.rnn.pack_padded_sequence` and `torch.nn.utils.rnn.pad_packed_sequence` to compress variable length sequences according to the longest sequence in a batch.
You can debug this module to see its working detail.

For more information of how this two function works, please search `pytorch variable length sequence`.

**Comment by GeneZC** [comment]
Now I get it.
