### ISSUE TITLE
如何计算模型的运行时间

### ISSUE THREAD

**Issue by FallingSlowly** [songyouwei/ABSA-PyTorch#34]
哈喽，请问如何计算单个模型的运行时间然后与其他模型进行比较呢？谢谢~

**Comment by songyouwei** [comment]
你可以直接使用python的时间函数，计算两个epoch之间的时间戳的差值。
不过每个模型实现细节都有所不同，更与底层模块优化有关，个人认为比较时间不是很有必要。
