### ISSUE TITLE
Hi~ 一直有个问题想问一下哈...

### ISSUE THREAD

**Issue by xuanzebi** [songyouwei/ABSA-PyTorch#35]
假如每个句子有不等个target（1-3个），需要预测出来每一个target的情感。。
想问下一下 假如每一个句子target不等的话，如何对齐呢...

我看好多论文最后都是过了softmax，这样的话是只能预测一个target的情感态度吗..

**Comment by GeneZC** [comment]
对的，对于同一个句子的不同aspect的情感，我们是将他们看作不同的sample看待的。
这样做很方便，但是却忽略了同一个句子中不同aspect的相互影响。

**Comment by xuanzebi** [comment]
非常感谢~
但是还是有点疑惑
如果看作不同的sample的话，那么输入是一个句子经过embedding，和aspect过embedding，（这里是将所有的aspect一起输入吗？）
然后经过一些attention机制，得到一个4分类（假如情感共4类）的结果，那么这个情感结果是哪个aspect的结果呢..

还有个疑问就是预测的时候，假如一个句子有三个aspect，如何对每一个aspect分别预测出各自的情感，是分成三份(一个句子+一个aspect)这样预测吗

因为我这方面略萌新，所以有些问题问的有点迷，不知道你能否看懂呢,,最后再次感谢

**Comment by GeneZC** [comment]
不是同时输入多个aspect。这里我们的一个sample其实只包括一个句子和一个aspect。

**Comment by xuanzebi** [comment]
那这样的话，假如一个句子有多个aspect,需要将其分成多个sample输入吗
这样的话 预测的话 一个句子假如有3个aspect，每次拿一个aspect预测，预测三次是这样的思路吗

**Comment by GeneZC** [comment]
Bingo！

**Comment by xuanzebi** [comment]
好的谢谢楼主 ~
follew你了 ~ haha
以后希望能多交流交流^^
