### ISSUE TITLE
关于测试间隔的设置

### ISSUE THREAD

**Issue by gaozhengjie** [songyouwei/ABSA-PyTorch#42]
您好，最近我在跑您基于 BERT 的 AEN 的代码，我发现您在训练的过程中是每间隔 5 个 step 就在测试集上进行一次测试，总共 20 个 epoch，那么这个过程中岂不是要测试非常多次，似乎有些耗时，这是否有必要呢？是否可以 1 个epoch跑完了之后再进行测试。另外，我使用 RTX 2080 Ti 跑您的 AEN-BERT 模型，batch_size 最大只能设为 16，我看您代码中写的是有16， 32 和 64 三种batch_size，不知道您在论文中的结果是用的多大的 batch_size。

望有空解惑，谢谢！:）

**Comment by songyouwei** [comment]
目前log_step的默认值5确实比较小，小数据集和小模型影响不太大，但大模型确实会慢一些，的确不必要测试太多。不过值得一提的是，小数据集的学习波动性比较大，相邻的epoch甚至step都可能会有明显差异。

训练基于BERT的模型，我batch_size设置的是32，使用的是GTX 1080Ti，单卡显存11G以上是可以的。
