### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by shanazkhan** [songyouwei/ABSA-PyTorch#45]
![Screenshot from 2019-05-02 11-27-34](https://user-images.githubusercontent.com/19191724/57035766-736a6400-6c70-11e9-8c73-674fe0c4e9ce.png)

**Comment by songyouwei** [comment]
Has the issue been solved?

**Comment by shanazkhan** [comment]
No.

**Comment by enterpine** [comment]
> No.

using 'bert-base-uncased' model need connect to amazon server to download ,you can get it from line 1 on outputs.

"Model name 'bert-base-uncased' was not found in model name......."

so connect to internet may solve your issue~
