### ISSUE TITLE
训练过程中损失函数的问题

### ISSUE THREAD

**Issue by LouZhiX** [songyouwei/ABSA-PyTorch#49]
您好，我想请问一下为什么在模型训练过程中损失函数曲线并不是单调递减的趋势，而是抖动下降的状态?起初我觉得是学习率衰减不够，但是修改之后发现并没有用.....
![image](https://user-images.githubusercontent.com/24652283/57664576-4ed89980-762b-11e9-955c-7c5776e0ea5c.png)

**Comment by songyouwei** [comment]
训练集上loss的抖动是正常的，尤其是使用的数据集比较小的情况下。
