### ISSUE TITLE
How to prepare my own text classification dataset?

### ISSUE THREAD

**Issue by aerinkim** [songyouwei/ABSA-PyTorch#52]
Hello authors, thank you for the nice, clean, running repo!
If I want to use the models to my own text classification dataset, what's the best way to prepare the data?
Specifically,

1) What is the best way to mask the aspects with `$T$`?
Currently what I have are just plain text and their labels.

2) Is there any way to use AEN_bert or BERT_spc without having to preprocess the data with `$T$`?

**Comment by songyouwei** [comment]
Data preprocessing is required, you need to do this by yourself.

**Comment by dgupta95** [comment]
Hello, 

I had the same issue. What I did was first get text you want to do sentiment analysis on. For me, it was in a pandas dataframe, with the text in one column and other metadata in another. 

First, you need to create a list of words you want to do aspect-based analysis on. These are your keywords. Alternatively, you can extract aspect from the sentence but I digress. 

Then you need to create a loop to go through the data and check in text where you have matches. When you have a match, also take the preceding and succeeding 200 characters (you can use other values, of course). My code looks like this: 


```
final_text = ''
for text in df.iloc[:,3]:
    #Replace newline with spaces to not fuck up our output formatting. 
    text = text.replace('\n', ' ')
    #Look for matches in text from list
    matches = [x for x in list_with_keywords if x in text]
    split_list = []
    
    for match in matches:
        #split the list according to the keyword
        split = text.split(match)
        for i in range(len(split)-1):
            #keep the first 200 characters on the left and right of the match. 
            # We format as the .xml.seg files in: 
            # https://github.com/songyouwei/ABSA-PyTorch/tree/master/datasets/semeval14
            final_text += split[i][-200:] + '$T$' + split[i+1][:200] + '\n' + match + '\n\n'
```

Finally, just write `final_text` to a text file. You can save it as an .xml.seg file.
