### ISSUE TITLE
Multi-Head Attention计算时不考虑位置编码？

### ISSUE THREAD

**Issue by BigHeartC** [songyouwei/ABSA-PyTorch#57]
请问在Multi-Head Attention计算时不考虑位置编码吗？我在代码中好像没找到，位置编码应该挺重要的吧

**Comment by songyouwei** [comment]
Multi-Head Attention 只是 Attention 的一种形式，位置编码应该在其他模块另外加进去，比如像 [RAM](https://github.com/songyouwei/ABSA-PyTorch/blob/master/models/ram.py) 模型这样
