### ISSUE TITLE
I think position embedding is important in sentiment analysis. Maybe adding position embdding in embedding layer makes figure more precise. 

### ISSUE THREAD

**Issue by Reusis** [songyouwei/ABSA-PyTorch#58]
I try to modify data_util.py, but there are some places that make me confused. I am caught in the bottleneck. So how to modify data_util.py to add position embedding?
Thanks

**Comment by songyouwei** [comment]
Please refer to the implementations of [RAM](https://github.com/songyouwei/ABSA-PyTorch/blob/master/models/ram.py) and [TNet](https://github.com/songyouwei/ABSA-PyTorch/blob/master/models/tnet_lf.py).
