### ISSUE TITLE
你好，mgan模块的 第32行  或者那个weight.appen(0)应该把0改成1 ？

### ISSUE THREAD

**Issue by LiuHongYi222** [songyouwei/ABSA-PyTorch#59]
因为mgan论文中，本意是要加大aspect词和靠近aspect的那些词的权重？

**Comment by GeneZC** [comment]
原文中提到

> Specifically, we treat the weights of words within the aspect as 0 in order to focus on the context words in the sentence

所以应该没问题哈。
