### ISSUE TITLE
experimental results

### ISSUE THREAD

**Issue by wuchaoml** [songyouwei/ABSA-PyTorch#60]
请问一下，直接运行你的aen模型，参数不断调整但是f1总是只有0.6左右，最多只有0.65，实在调不到你的水平，可以将你修改的参数值发一下吗，参考一下，谢谢了

**Comment by songyouwei** [comment]
猜测是学习率设置的问题。AEN-BERT和BERT-SPC使用2e-5的学习率，AEN-GloVe等其他非基于BERT的模型使用1e-3的学习率。
https://github.com/songyouwei/ABSA-PyTorch/blob/a736bf1cc07e4509fe60e986dbe9b8658d153817/train.py#L183

**Comment by wuchaoml** [comment]
我也是这样设置的，但是aen基本模型在两个数据集上的效果都是要差5到10个百分点，bert-spc模型结果是没有问题的。

**Comment by songyouwei** [comment]
非基于BERT的模型在小数据集上的训练过程不太稳定，IAN、MemNet、RAM、TNet等模型在使用[先前的实验方法](https://github.com/songyouwei/ABSA-PyTorch/blob/dc62dc615100218fe7daf8f60dcda80ef2f52ace/train.py#L101)时，可以达到这些论文原文贴出来的结果。原则上来说，这种实验方法不够严谨，需要较大的epoch，也难以复现。
目前repo推荐的实验方法包括两种，一是[仅在epoch结尾做验证](https://github.com/songyouwei/ABSA-PyTorch/blob/a736bf1cc07e4509fe60e986dbe9b8658d153817/train.py#L119)，二是[使用K折交叉验证的方法得到结果的均值](https://github.com/songyouwei/ABSA-PyTorch/blob/a736bf1cc07e4509fe60e986dbe9b8658d153817/train_k_fold_cross_val.py#L155)。这时候的结果不会是“最好的”，通常会差3到5个百分点。

**Comment by wuchaoml** [comment]
原来是这样啊，那我再尝试看看，想想看有没有其他改进的地方，谢谢大佬的回复了，非常的专业
