### ISSUE TITLE
关于aen-bert模型的实验结果复现

### ISSUE THREAD

**Issue by LiuHongYi222** [songyouwei/ABSA-PyTorch#62]
作者你好。
在尝试了很多实验之后， aen-bert模型复现遇到了一些瓶颈。
学习率尝试了很多，包括2,3,5e-5等等，     epoch也适当增加了多轮次（到了20.30+）

自己的多次实验表明：
res数据集最高只能到82.4的准确率（论文是83.12）
lap数据集最高只能到78.4的准确率（论文是79.93），此结果差别较大

想请问一下是不是我自己操作哪里有问题。
能否麻烦您详细把训练的超参再说明一下。

谢谢。

**Comment by songyouwei** [comment]
因为先前的实验方法不够严谨，所有结果会有一点出入。推荐大家都采用目前repo中最新的实验方法，个人推荐[使用10折交叉验证](https://github.com/songyouwei/ABSA-PyTorch/blob/a736bf1cc07e4509fe60e986dbe9b8658d153817/train_k_fold_cross_val.py#L155)得到的结果。
参照[这个回复](https://github.com/songyouwei/ABSA-PyTorch/issues/60#issuecomment-496877114)。

**Comment by songyouwei** [comment]
#60
