### ISSUE TITLE
how to run a bert-based model

### ISSUE THREAD

**Issue by xiliu-m** [songyouwei/ABSA-PyTorch#66]
after install the pytorch-pretrained-bert 0.6.1, and loading vocabulary file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt , it shows:
https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased.tar.gz not found in cache, downloading to /tmp/tmpzqs03pcr
want to know whether I can install the tar.gz in advance? and how?

**Comment by songyouwei** [comment]
You can set **a path or url to a pretrained model archive** to the `from_pretrained()` method. See [this link](https://github.com/huggingface/pytorch-pretrained-BERT#from_pretrained-method).

**Comment by xiliu-m** [comment]
Thank you for your reply! But after I download from AWS S3, I couldn't find the file: pytorch_model.bin a PyTorch dump of a pre-trained instance of BertForPreTraining, OpenAIGPTModel, TransfoXLModel, GPT2LMHeadModel (saved with the usual torch.save())
emm, how to solve it?

**Comment by songyouwei** [comment]
Is it possible that your network problem caused you to fail to download successfully?

**Comment by xiliu-m** [comment]
Thanks. I have solved the problem by using the 
 function: convert_tf_checkpoint_to_pytorch('../bert/bert_model.ckpt', '../bert/bert_config.json', '../bert/pytorch_model.bin')
