### ISSUE TITLE
The CABSAC‘s model have some bugs, I have the loss 0

### ISSUE THREAD

**Issue by cyzLoveDream** [songyouwei/ABSA-PyTorch#7]
the .py file don't have run...I want to say, you haven't run it?

**Comment by saja1994** [comment]
Are the running results are the same as mentioned in the papers? Because I have a problem with my laptop and I need just to make sure that this implementation is accurate?

**Comment by songyouwei** [comment]
@saja1994 In my experiment, some models did not perform well on laptop dataset. If you found some problem of my implementation, please make a Pull Request.

**Comment by saja1994** [comment]
Thank you, I am asking because I need this implementation to help me in my master's thesis. So I need an accurate code and I have a laptop with regular specs ( 8 RAM ). I am waiting to buy a new one to do my implementation. If I found any problem I well for sure ask you.

Thanks again,
