### ISSUE TITLE
About the squeeze_smbedding.py

### ISSUE THREAD

**Issue by cyzLoveDream** [songyouwei/ABSA-PyTorch#76]
感谢git主分享这个repo，我看这个文件里面对传入的x进行了压缩之后又解压，相当于没有做任何操作，那么这个还有必要使用吗

**Comment by songyouwei** [comment]
#31 
对一个batch的zero padding做压缩的，不是必须。举个栗子：

输入：
1 2 3 4 0 0 0
1 0 0 0 0 0 0
1 2 3 0 0 0 0

输出：
1 2 3 4
1 0 0 0
1 2 3 0
