### ISSUE TITLE
Another Languages

### ISSUE THREAD

**Issue by saja1994** [songyouwei/ABSA-PyTorch#8]
Thank you so much for your efforts, but I have a question (Do you think that these models could work with datasets in other languages such as Arabic?)

Regards,
Saja

**Comment by songyouwei** [comment]
I think these models works for all other languages, just use different word embeddings.

You may have a try.

**Comment by saja1994** [comment]
Thank you I will try.

**Comment by saja1994** [comment]
Hello,
please, when I run these models using the provided data-sets almost the results were lower than the reported in the original papers by 2 or 3. So, have you any explanation about that?

Thanks a lot,

**Comment by dgupta95** [comment]
Short question: When you train other languages, do I need to only change the pretrained_bert_name?
