### ISSUE TITLE
How to solve this?

### ISSUE THREAD

**Issue by ShuvamChatterjee28** [songyouwei/ABSA-PyTorch#86]
I just run this in cmd and I got this result, ` File "train.py", line 14, in <module>
    from pytorch_pretrained_bert import BertModel
ModuleNotFoundError: No module named 'pytorch_pretrained_bert'` 
can any of you please me solve this issue?

**Comment by songyouwei** [comment]
Do you have `pytorch-pretrained-BERT` installed?

**Comment by cyzLoveDream** [comment]
now it have been changed pytorch-transformer. you can modify your code

**Comment by songyouwei** [comment]
@cyzLoveDream could you please make a pull request to fix this?

**Comment by SaiThejeshwar** [comment]
@songyouwei I made a pull request to fix this issue. Hope we can close the issue soon.

**Comment by songyouwei** [comment]
@SaiThejeshwar This repo has migrated to `pytorch-transformers`.
Thank u for your contribution, but simply changes `pytorch-transformers` to `transformers` may have serious performance issues. 
FYI:  https://github.com/songyouwei/ABSA-PyTorch/issues/27#issuecomment-551058509

**Comment by SaiThejeshwar** [comment]
@songyouwei  Thank you for letting me know. I didn't think it had performance issues. #27
