### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by a390138773** [songyouwei/ABSA-PyTorch#87]
semeval的数据集下载的默认格式好像是xml  请问是如何处理成提供的seg文件  或者是哪里有处理好的下载？ 因为还想试试其他semeval15的数据集效果

**Comment by songyouwei** [comment]
Please refer to issue #73

**Comment by a390138773** [comment]
感谢

**Comment by a390138773** [comment]
这个主页是只提供了14年的semval的seg数据集 没有处理文件 如果我需要其他尝试其他数据集是不是需要修改一下您的处理代码

**Comment by songyouwei** [comment]
> 这个主页是只提供了14年的semval的seg数据集 没有处理文件 如果我需要其他尝试其他数据集是不是需要修改一下您的处理代码

我没有处理的代码。这个处理还是比较容易的吧，你可以自己做一下

**Comment by a390138773** [comment]
> > 这个主页是只提供了14年的semval的seg数据集 没有处理文件 如果我需要其他尝试其他数据集是不是需要修改一下您的处理代码
> 
> 我没有处理的代码。这个处理还是比较容易的吧，你可以自己做一下

好的 谢谢
